### ISSUE TITLE
TODO Extranet Ran Coper

### ISSUE THREAD

**Issue by pabois** [osunyorg/admin#876]
### Droits / comptes

- [ ] permettre de scoper les droits de connexion aux alumni ou a autre chose
- [ ] Vérifier le processus d'onboarding (inscription / connexion)
- [ ] Vérifier les droits des utilisateurs
- [ ] Modifier les expériences -> alumni only

### Setup Extranet

- [ ] différencier les différents champs selon droits
- [ ] home sentence à traduire et à passer en summernote

### Actualités

- [ ] categories
- [ ] pagination
- [ ] cadrage image
- [ ] (search)

### Documents

- [ ] fichiers
- [ ] types
- [ ] categories
- [ ] (search)

### Annuaire

- [ ] connexion personnes / orgas -> les expériences doivent redescende au niveau de la personne
